# TCL File Generated by Component Editor 18.1
# Tue Apr 05 19:23:59 EEST 2022
# DO NOT MODIFY


# 
# avalon_MM_export_bridge "avalon_MM_export_bridge" v1.0
#  2022.04.05.19:23:59
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_MM_export_bridge
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_MM_export_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_MM_export_bridge
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_MM_export_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_MM_export_bridge.vhd VHDL PATH avalon_MM_export_bridge.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter addr_width NATURAL 5 ""
set_parameter_property addr_width DEFAULT_VALUE 5
set_parameter_property addr_width DISPLAY_NAME addr_width
set_parameter_property addr_width WIDTH ""
set_parameter_property addr_width TYPE NATURAL
set_parameter_property addr_width UNITS None
set_parameter_property addr_width ALLOWED_RANGES 0:2147483647
set_parameter_property addr_width DESCRIPTION ""
set_parameter_property addr_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clk_i clk Input 1


# 
# connection point clock_source
# 
add_interface clock_source clock start
set_interface_property clock_source associatedDirectClock ""
set_interface_property clock_source clockRate 0
set_interface_property clock_source clockRateKnown false
set_interface_property clock_source ENABLED true
set_interface_property clock_source EXPORT_OF ""
set_interface_property clock_source PORT_NAME_MAP ""
set_interface_property clock_source CMSIS_SVD_VARIABLES ""
set_interface_property clock_source SVD_ADDRESS_GROUP ""

add_interface_port clock_source clk_o clk Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink i_reset reset Input 1


# 
# connection point reset_source
# 
add_interface reset_source reset start
set_interface_property reset_source associatedClock clock_sink
set_interface_property reset_source associatedDirectReset ""
set_interface_property reset_source associatedResetSinks ""
set_interface_property reset_source synchronousEdges DEASSERT
set_interface_property reset_source ENABLED true
set_interface_property reset_source EXPORT_OF ""
set_interface_property reset_source PORT_NAME_MAP ""
set_interface_property reset_source CMSIS_SVD_VARIABLES ""
set_interface_property reset_source SVD_ADDRESS_GROUP ""

add_interface_port reset_source o_reset reset Output 1


# 
# connection point i_mmi
# 
add_interface i_mmi avalon end
set_interface_property i_mmi addressUnits WORDS
set_interface_property i_mmi associatedClock clock_sink
set_interface_property i_mmi associatedReset ""
set_interface_property i_mmi bitsPerSymbol 8
set_interface_property i_mmi burstOnBurstBoundariesOnly false
set_interface_property i_mmi burstcountUnits WORDS
set_interface_property i_mmi explicitAddressSpan 0
set_interface_property i_mmi holdTime 0
set_interface_property i_mmi linewrapBursts false
set_interface_property i_mmi maximumPendingReadTransactions 0
set_interface_property i_mmi maximumPendingWriteTransactions 0
set_interface_property i_mmi readLatency 0
set_interface_property i_mmi readWaitTime 1
set_interface_property i_mmi setupTime 0
set_interface_property i_mmi timingUnits Cycles
set_interface_property i_mmi writeWaitTime 0
set_interface_property i_mmi ENABLED true
set_interface_property i_mmi EXPORT_OF ""
set_interface_property i_mmi PORT_NAME_MAP ""
set_interface_property i_mmi CMSIS_SVD_VARIABLES ""
set_interface_property i_mmi SVD_ADDRESS_GROUP ""

add_interface_port i_mmi i_mmi_write write Input 1
add_interface_port i_mmi i_mmi_read read Input 1
add_interface_port i_mmi i_mmi_address address Input 5
add_interface_port i_mmi i_mmi_writedata writedata Input 32
add_interface_port i_mmi i_mmi_byteenable byteenable Input 4
add_interface_port i_mmi o_mmi_readdata readdata Output 32
set_interface_assignment i_mmi embeddedsw.configuration.isFlash 0
set_interface_assignment i_mmi embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment i_mmi embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment i_mmi embeddedsw.configuration.isPrintableDevice 0


# 
# connection point o_mmo
# 
add_interface o_mmo avalon start
set_interface_property o_mmo addressUnits SYMBOLS
set_interface_property o_mmo associatedClock clock_sink
set_interface_property o_mmo associatedReset ""
set_interface_property o_mmo bitsPerSymbol 8
set_interface_property o_mmo burstOnBurstBoundariesOnly false
set_interface_property o_mmo burstcountUnits WORDS
set_interface_property o_mmo doStreamReads false
set_interface_property o_mmo doStreamWrites false
set_interface_property o_mmo holdTime 0
set_interface_property o_mmo linewrapBursts false
set_interface_property o_mmo maximumPendingReadTransactions 0
set_interface_property o_mmo maximumPendingWriteTransactions 0
set_interface_property o_mmo readLatency 0
set_interface_property o_mmo readWaitTime 1
set_interface_property o_mmo setupTime 0
set_interface_property o_mmo timingUnits Cycles
set_interface_property o_mmo writeWaitTime 0
set_interface_property o_mmo ENABLED true
set_interface_property o_mmo EXPORT_OF ""
set_interface_property o_mmo PORT_NAME_MAP ""
set_interface_property o_mmo CMSIS_SVD_VARIABLES ""
set_interface_property o_mmo SVD_ADDRESS_GROUP ""

add_interface_port o_mmo o_mmo_write write Output 1
add_interface_port o_mmo o_mmo_read read Output 1
add_interface_port o_mmo o_mmo_address address Output 5
add_interface_port o_mmo o_mmo_writedata writedata Output 32
add_interface_port o_mmo o_mmo_byteenable byteenable Output 4
add_interface_port o_mmo o_mmo_readdata readdata Input 32

